export default [
  {
    id: '123456789',
    orderReference: 'none',
    orderContent: 'none',
    amount: '1234567890',
    paymentMethod: 'Bank',
    bank: 'Vietcombank',
    status: 'Pending',
    salesResponsible: 'none',
    processedBy: 'none',
    title: 'none',
    customerName: 'none',
    email: 'none',
    phone: '0123456789 ',
    checkFormat: 'none',
  },
  {
    id: '123456789',
    orderReference: 'none',
    orderContent: 'none',
    amount: '1234567890',
    paymentMethod: 'Cash',
    bank: 'Vietcombank',
    status: 'Pending',
    salesResponsible: 'none',
    processedBy: 'none',
    title: 'none',
    customerName: 'none',
    email: 'none',
    phone: '0123456789 ',
    checkFormat: 'none',
  },
  {
    id: '123456789',
    orderReference: 'none',
    orderContent: 'none',
    amount: '1234567890',
    paymentMethod: 'Cash',
    bank: 'Vietcombank',
    status: 'Pending',
    salesResponsible: 'none',
    processedBy: 'none',
    title: 'none',
    customerName: 'none',
    email: 'none',
    phone: '0123456789 ',
    checkFormat: 'none',
  },
];
