export default {
  START_QUERY: 'START_QUERY',
  END_QUERY: 'END_QUERY',

  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  GET_SUCCESS_SMS: 'GET_SUCCESS_SMS',
  GET_FAILURE_SMS: 'GET_FAILURE_SMS',
  EDIT_SMS_SUCCESS: 'EDIT_SMS_SUCCESS',
  EDIT_SMS_FAILURE: 'EDIT_SMS_FAILURE',

  GET_SUCCESS_SMS_DETAIL: 'GET_SUCCESS_SMS_DETAIL',
  GET_FAILURE_SMS_DETAIL: 'GET_FAILURE_SMS_DETAIL',

  PUT_SUCCESS_SMS_DETAIL: 'PUT_SUCCESS_SMS_DETAIL',
  PUT_FAILURE_SMS_DETAIL: 'PUT_FAILURE_SMS_DETAIL',

  GET_ACCOUNT_SUCCESS: 'GET_ACCOUNT_SUCCESS',
  GET_ACCOUNT_FAILURE: 'GET_ACCOUNT_FAILURE',

  POST_ACCOUNT_SUCCESS: 'POST_ACCOUNT_SUCCESS',
  POST_ACCOUNT_FAILURE: 'POST_ACCOUNT_FAILURE',

  EDIT_ACCOUNT_SUCCESS: 'EDIT_ACCOUNT_SUCCESS',
  EDIT_ACCOUNT_FAILURE: 'EDIT_ACCOUNT_FAILURE',

  DEL_ACCOUNT_SUCCESS: 'DEL_ACCOUNT_SUCCESS',
  DEL_ACCOUNT_FAILURE: 'DEL_ACCOUNT_FAILURE',

  EDIT_PASSWORD_SUCCESS: 'EDIT_PASSWORD_SUCCESS',
  EDIT_PASSWORD_FAILURE: 'EDIT_PASSWORD_FAILURE',

  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'REST_PASSWORD_FAILURE',

  GET_SUCCESS_REPORT: 'GET_SUCCESS_REPORT',
  GET_FAILURE_REPORT: 'GET_FAILURE_REPORT',
};
