export default  {
    START_QUERY: 'START_QUERY',
    END_QUERY: 'END_QUERY',

    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    GET_SUCCESS_SMS : 'GET_SUCCESS_SMS',
    GET_FAILURE_SMS : 'GET_FAILURE_SMS',

    GET_SUCCESS_SMS_DETAIL : 'GET_SUCCESS_SMS_DETAIL',
    GET_FAILURE_SMS_DETAIL : 'GET_FAILURE_SMS_DETAIL',

    PUT_SUCCESS_SMS_DETAIL : 'PUT_SUCCESS_SMS_DETAIL',
    PUT_FAILURE_SMS_DETAIL : 'PUT_FAILURE_SMS_DETAIL',

    GET_SUCCESS_ACCOUNT : 'GET_SUCCESS_ACCOUNT',
    GET_FAILURE_ACCOUNT : 'GET_FAILURE_ACCOUNT',

    POST_SUCCESS_ACCOUNT : 'POST_SUCCESS_ACCOUNT',
    POST_FAILURE_ACCOUNT : 'POST_FAILURE_ACCOUNT',

    PUT_SUCCESS_ACCOUNT_DETAIL : 'PUT_SUCCESS_ACCOUNT_DETAIL',
    PUT_FAILURE_ACCOUNT_DETAIL : 'PUT_FAILURE_ACCOUNT_DETAIL',

    DEL_SUCCESS_ACCOUNT_DETAIL : 'DEL_SUCCESS_ACCOUNT_DETAIL',
    DEL_FAILURE_ACCOUNT_DETAIL : 'DEL_FAILURE_ACCOUNT_DETAIL',

    GET_SUCCESS_REPORT : 'GET_SUCCESS_REPORT',
    GET_FAILURE_REPORT : 'GET_FAILURE_REPORT',
}